"""Core domain models for CortexShift."""

from cortexshift.domain.checkpoint import Checkpoint
from cortexshift.domain.doctor import (
    AuthenticationStatus,
    DoctorReport,
    PlatformInfo,
    ProviderDiagnostic,
)
from cortexshift.domain.errors import (
    CortexShiftError,
    DatabaseStateError,
    GitNotInstalledError,
    GitProbeError,
    GitProbeTimeoutError,
    HandoffDeliveryError,
    HandoffNotFoundError,
    NoActiveTaskError,
    NoSourceSessionError,
    NotAGitRepositoryError,
    ProjectAlreadyInitializedError,
    ProjectConflictError,
    ProjectNotInitializedError,
    ProviderNotFoundError,
    RepositoryInspectionError,
    SameProviderSwitchError,
    SessionNotFoundError,
    SessionTaskMismatchError,
    SnapshotNotFoundError,
    StateCorruptionError,
    TaskAlreadyCompletedError,
    TaskNotActivatableError,
    TaskNotFoundError,
    TerminalRequiredError,
    UnknownProviderError,
    UnsupportedPromptError,
    UnsupportedSchemaVersionError,
    WorkspaceLockedError,
)
from cortexshift.domain.git import GitSnapshot, RepositoryInspection, RepositoryInspectionStatus
from cortexshift.domain.handoff import (
    HANDOFF_PROTOCOL_VERSION,
    HandoffFailureCode,
    HandoffGitState,
    HandoffPayload,
    HandoffRecord,
    HandoffSourceSession,
    HandoffStatus,
    HandoffTestStatus,
)
from cortexshift.domain.identifiers import generate_id, utc_now
from cortexshift.domain.launch import LaunchSpecification
from cortexshift.domain.project import Project
from cortexshift.domain.provider import (
    PROVIDER_ANTIGRAVITY,
    PROVIDER_CLAUDE,
    PROVIDER_CODEX,
    ProviderCapabilities,
    ProviderId,
)
from cortexshift.domain.session import Session, SessionExitReason, SessionStatus
from cortexshift.domain.status import ActiveTaskSummary, ProgressSummary, ProjectStatus
from cortexshift.domain.task import Task, TaskStatus

__all__ = [
    "ActiveTaskSummary",
    "AuthenticationStatus",
    "Checkpoint",
    "CortexShiftError",
    "DatabaseStateError",
    "DoctorReport",
    "GitNotInstalledError",
    "GitProbeError",
    "GitProbeTimeoutError",
    "GitSnapshot",
    "HandoffDeliveryError",
    "HandoffFailureCode",
    "HandoffGitState",
    "HandoffNotFoundError",
    "HandoffPayload",
    "HandoffRecord",
    "HandoffSourceSession",
    "HandoffStatus",
    "HandoffTestStatus",
    "LaunchSpecification",
    "NoActiveTaskError",
    "NoSourceSessionError",
    "NotAGitRepositoryError",
    "PlatformInfo",
    "ProgressSummary",
    "Project",
    "ProjectAlreadyInitializedError",
    "ProjectConflictError",
    "ProjectNotInitializedError",
    "ProjectStatus",
    "ProviderCapabilities",
    "ProviderDiagnostic",
    "ProviderId",
    "ProviderNotFoundError",
    "RepositoryInspection",
    "RepositoryInspectionError",
    "RepositoryInspectionStatus",
    "SameProviderSwitchError",
    "Session",
    "SessionExitReason",
    "SessionNotFoundError",
    "SessionStatus",
    "SessionTaskMismatchError",
    "SnapshotNotFoundError",
    "StateCorruptionError",
    "Task",
    "TaskAlreadyCompletedError",
    "TaskNotActivatableError",
    "TaskNotFoundError",
    "TaskStatus",
    "TerminalRequiredError",
    "UnknownProviderError",
    "UnsupportedPromptError",
    "UnsupportedSchemaVersionError",
    "WorkspaceLockedError",
    "HANDOFF_PROTOCOL_VERSION",
    "PROVIDER_ANTIGRAVITY",
    "PROVIDER_CLAUDE",
    "PROVIDER_CODEX",
    "generate_id",
    "utc_now",
]
