"""Domain models for environment inspection and provider diagnostics."""

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from cortexshift.domain.provider import ProviderCapabilities, ProviderId


class AuthenticationStatus(StrEnum):
    """Status of provider CLI authentication."""

    AUTHENTICATED = "authenticated"
    NOT_AUTHENTICATED = "not_authenticated"
    UNKNOWN = "unknown"
    NOT_PROBED = "not_probed"


class PlatformInfo(BaseModel):
    """System and environment metadata for diagnostics."""

    model_config = ConfigDict(frozen=True)

    system: str
    release: str
    machine: str
    python_version: str


class ProviderDiagnostic(BaseModel):
    """Diagnostic health and capability record for a single provider CLI."""

    model_config = ConfigDict(frozen=True)

    provider_id: ProviderId
    display_name: str
    executable: str
    installed: bool
    resolved_path: str | None = None
    version: str | None = None
    authentication_status: AuthenticationStatus = AuthenticationStatus.UNKNOWN
    capabilities: ProviderCapabilities
    diagnostics: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def id(self) -> ProviderId:
        """Alias for provider_id for serialization convenience."""
        return self.provider_id

    @property
    def authentication(self) -> AuthenticationStatus:
        """Alias for authentication_status."""
        return self.authentication_status


class DoctorReport(BaseModel):
    """Aggregate diagnostic report generated by `cortexshift doctor`."""

    model_config = ConfigDict(frozen=True)

    cortexshift_version: str
    python_version: str
    platform: PlatformInfo
    timestamp: datetime
    providers: list[ProviderDiagnostic]
